export const post_type = {
  GET_POSTS: 'GET_POSTS',
  GET_SINGLE_POST: 'GET_SINGLE_POST',
  GET_FILTERED_POSTS: 'GET_FILTERED_POSTS',
  CREATE_POST: 'CREATE_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  REMOVE_SINGLE_POST: 'REMOVE_SINGLE_POST',
}

export const drawer_type = {
  CLOSE_DRAWER: 'CLOSE_DRAWER',
  OPEN_DRAWER: 'OPEN_DRAWER',
}
