export const product_type = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',
  GET_FILTERED_PRODUCTS: 'GET_FILTERED_PRODUCTS',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  REMOVE_SINGLE_PRODUCT: 'REMOVE_SINGLE_PRODUCT',
}

export const drawer_type = {
  CLOSE_DRAWER: 'CLOSE_DRAWER',
  OPEN_DRAWER: 'OPEN_DRAWER',
}
